networks:
  wg:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
    enable_ipv6: false
    attachable: true

services:
  wg-easy:
#    build:
#      context: .
#      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Moscow
      - DISABLE_IPV6=true
    image: reg.vados.ru/wg-easy/wg-easy:v15.0.3-rb-gh
    env_file:
      - path: ./.env
        required: true
    container_name: wg-easy
    networks:
      wg:
        interface_name: eth0
        ipv4_address: 10.42.42.42
      traefik:
        interface_name: eth1
    volumes:
      - ~/.wg-easy:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "29185:29185/udp"
      - "8588:8588/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.all.forwarding=0
      - net.ipv6.conf.default.forwarding=0


#        interface_name: eth0
#        gw_priority: 0
#        ipv4_address: 10.42.42.42
#        ipv6_address: fdcc:ad94:bacf:61a3::2a



#volumes:
#  dockge_data:
#networks:
#  swarm_net:
#    name: swarm_net
#    driver: overlay


#volumes:
#  etc_wireguard:
#      - etc_wireguard:/etc/wireguard

#volumes:
#  /etc/wireguard:


#      - LANG=ru:
#      # .. Required:
#      # Change this to your host's public address
#      # - WG_HOST=89.110.101.17
#      # - WG_HOST=10.30.30.33
#      - HOST=10.30.30.33
#      # Optional:
#      # - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG # (needs double $$, hash of 'foobar123'; see "How_to_generate_an_bcrypt_hash.md" for generate the hash)
#      - PASSWORD_HASH=$2a$12$5sWStJ8xjBrDJNY.0TJye.ENJ5Ml9wL.1MnTB7E7284P83RpXQ7SW
#      # - PORT=51821
#      - PORT=8588
#      # - WG_PORT=51820
#      - WG_PORT=29185
#      # - WG_CONFIG_PORT=92820
#      - WG_DEFAULT_ADDRESS=10.8.0.1
#      # - WG_DEFAULT_DNS=1.1.1.1
#      - WG_DEFAULT_DNS=8.8.8.8, 1.1.1.1
#      - WG_MTU=1420
#      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
#      - WG_PERSISTENT_KEEPALIVE=25
#      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
#      - WG_POST_UP=/etc/wireguard/post-up.txt
#      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
#      - WG_POST_DOWN=/etc/wireguard/post-down.txt
#      - UI_TRAFFIC_STATS=true
#      - UI_CHART_TYPE=3 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
#      - INSECURE=false

      # - NET_RAW # ⚠️ Uncomment if using Podman