networks:
  wg:
    external: true
  traefik:
    external: true

services:
  adguard:
    image: adguard/adguardhome:v0.107.64
    container_name: adguard
    restart: unless-stopped
    volumes:
      - /etc/docker/volumes/adguard/adguard_work:/opt/adguardhome/work
      - /etc/docker/volumes/adguard/adguard_conf:/opt/adguardhome/conf
    networks:
      wg:
        interface_name: eth0
        ipv4_address: 10.42.42.43
#        ipv6_address: fdcc:ad94:bacf:61a3::2b
      traefik:
        interface_name: eth1
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.adguard.rule=Host(`adguard.vados.ru`)'
      - 'traefik.http.routers.adguard.entrypoints=websecure'
      - 'traefik.http.routers.adguard.service=adguard'
      - 'traefik.http.services.adguard.loadbalancer.server.port=3000'
      - 'traefik.docker.network=traefik'

