name: Deploy

permissions:
  contents: write
  packages: write

env:
  DEFAULT_PUBLISH_REPOS: true

on:
  #  workflow_call:
  push:
    branches:
      - "**"
    tags:
      - "v*.*."
  #   schedule:
  #     - cron: "17 * * 3 1"
  workflow_dispatch:
    inputs:
      force_build:
        description: "Force build or generate-matrix even if version is unchanged"
        required: true
        default: true
        type: boolean
      from_tag:
        description: "Build tag for the Docker image"
        required: true
        default: "15.0.3"
        type: string

# This workflow does not support fixing old versions
# as this will break the latest and major tags

jobs:
  docker-build:
    name: Build Docker
    runs-on: ${{ matrix.arch.os }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - platform: linux/amd64
            os: ubuntu-latest
          #- platform: linux/arm64
          #  os: ubuntu-24.04-arm
          # - platform: linux/arm/v7
          #   os: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6

      - name: Prepare
        run: |
          platform=${{ matrix.arch.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ghcr.io/vados-dev/wg-easy
          tags: |
            type=ref,event=tag
            type=pep440,pattern={{raw}}
            type=pep440,pattern={{majorr}}.{{minor}}.{{patch}}
            type=raw,${{ inputs.build_tag }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: ${{ matrix.arch.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ghcr.io/vados-dev/wg-easy
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true
          cache-from: type=gha,scope=build-${{ env.PLATFORM_PAIR }}
          cache-to: type=gha,mode=min,scope=build-${{ env.PLATFORM_PAIR }}

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v7
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  docker-merge:
    name: Merge & Deploy Docker
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v8
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: |
            ghcr.io/vados-dev/wg-easy
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf 'ghcr.io/vados-dev/wg-easy@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ghcr.io/vados-dev/wg-easy:${{ steps.meta.outputs.version }}
