name: Build & Deploy

env:
  DEFAULT_BRANCH: master
  REGISTRY_IMAGE: ghcr.io/vados-dev/wg-easy
#  DEFAULT_PUBLISH_REPOS: true

on:
  #  workflow_call:
  #   schedule:
  #     - cron: "17 * * 3 1"
  push:
    branches: [ "master" ]
    tags: [ "[0-9]+.[0-9]+.[0-9]+", "v15-rb.lts", "v*.*." ]

  workflow_dispatch:
    inputs:
      from_branch:
        description: "Branch for build and deploy"
        required: true
        default: "master"
        type: string
      build_images:
        description: "Image name for buld targrest."
        required: true
        default: "wg-easy"
        type: string
      build_tag:
        description: "Build tag for the Docker image"
        required: true
        default: "v15-rb.lts"
        type: string
      build_platforms:
        description: "Build platforms e.g.
          (linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8)"
        required: true
        default: "linux/amd64"
        type: string

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: github.repository_owner == 'vados-dev'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{inputs.from_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v7
        with:
          context: .
          platforms: ${{inputs.build_platforms}}
          cache-from: type=gha,scope=build-${{ env.PLATFORM_PAIR }}
          cache-to: type=gha,mode=min,scope=build-${{ env.PLATFORM_PAIR }}
          tags: |
            - ghcr.io/vados-dev/${{inputs.build_images}}:latest
              ghcr.io/vados-dev/${{inputs.build_images}}:${{inputs.build_tag}}
              ${{ env.REGISTRY_IMAGE }}
          labels: |
            - ${{ steps.build.outputs.labels }}
              maintainer={{ github.actor }}
              org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
              org.opencontainers.image.revision={{commit_short}}
              org.opencontainers.image.version={{version}}
              org.opencontainers.image.url={{url}}
              org.opencontainers.image.source={{url}}
              org.opencontainers.image.documentation={{url}}            
          outputs: type=image,push-by-digest=false,name-canonical=true,push=true

